services:
  - type: web
    name: vd-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POLLINATIONS_KEY
        value: sk_qGTE6yG58UawexsyAcoQwpi0CDGWaF2o
      - key: POLLINATIONS_PK
        value: pk_j1VCcxAp2GYeMzyx
      - key: HF_TOKEN
        sync: false

